export const ORDER_STATUS = Object.freeze({
  CREATED: 'CREATED',
  SEARCHING: 'SEARCHING',
  ASSIGNED: 'ASSIGNED',
  WORKER_ARRIVING: 'WORKER_ARRIVING',
  ARRIVED: 'ARRIVED',
  IN_PROGRESS: 'IN_PROGRESS',
  AWAITING_CONFIRMATION: 'AWAITING_CONFIRMATION',
  AWAITING_PAYMENT: 'AWAITING_PAYMENT',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

export const VALID_STATUS_TRANSITIONS = Object.freeze({
  [ORDER_STATUS.CREATED]: [ORDER_STATUS.SEARCHING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.SEARCHING]: [ORDER_STATUS.ASSIGNED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.ASSIGNED]: [
    ORDER_STATUS.WORKER_ARRIVING,
    ORDER_STATUS.SEARCHING,
    ORDER_STATUS.CANCELLED,
  ],
  [ORDER_STATUS.WORKER_ARRIVING]: [
    ORDER_STATUS.ARRIVED,
    ORDER_STATUS.CANCELLED,
  ],
  [ORDER_STATUS.ARRIVED]: [
    ORDER_STATUS.IN_PROGRESS,
    ORDER_STATUS.CANCELLED,
  ],
  [ORDER_STATUS.IN_PROGRESS]: [
    ORDER_STATUS.AWAITING_CONFIRMATION,
    ORDER_STATUS.CANCELLED,
  ],
  [ORDER_STATUS.AWAITING_CONFIRMATION]: [
    ORDER_STATUS.AWAITING_PAYMENT,
    ORDER_STATUS.IN_PROGRESS,
    ORDER_STATUS.CANCELLED,
  ],
  [ORDER_STATUS.AWAITING_PAYMENT]: [
    ORDER_STATUS.COMPLETED,
    ORDER_STATUS.CANCELLED,
  ],
  [ORDER_STATUS.COMPLETED]: [],
  [ORDER_STATUS.CANCELLED]: [],
});
