export const ORDER_STATUS = Object.freeze({
  PENDING: 'PENDING',
  MATCHED: 'MATCHED',
  WORKER_ACCEPTED: 'WORKER_ACCEPTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
  DISPUTED: 'DISPUTED',
});

export const VALID_STATUS_TRANSITIONS = Object.freeze({
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.MATCHED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.MATCHED]: [
    ORDER_STATUS.WORKER_ACCEPTED,
    ORDER_STATUS.PENDING,
    ORDER_STATUS.CANCELLED,
  ],
  [ORDER_STATUS.WORKER_ACCEPTED]: [
    ORDER_STATUS.IN_PROGRESS,
    ORDER_STATUS.CANCELLED,
  ],
  [ORDER_STATUS.IN_PROGRESS]: [
    ORDER_STATUS.COMPLETED,
    ORDER_STATUS.DISPUTED,
    ORDER_STATUS.CANCELLED,
  ],
  [ORDER_STATUS.COMPLETED]: [
    ORDER_STATUS.PAYMENT_CONFIRMED,
    ORDER_STATUS.DISPUTED,
  ],
  [ORDER_STATUS.PAYMENT_CONFIRMED]: [ORDER_STATUS.CLOSED],
  [ORDER_STATUS.CLOSED]: [],
  [ORDER_STATUS.CANCELLED]: [],
  [ORDER_STATUS.DISPUTED]: [ORDER_STATUS.CLOSED, ORDER_STATUS.CANCELLED],
});
